### ISSUE TITLE
Ability to create two Users (different usernames) with the same "Email" and "Phone Number"

### ISSUE THREAD

**Issue by KarthikVV24-11-1999** [gcivil-nyu-org/fall24-monday-team5#85]
After creating a new account with the username [Karthik], email [venkatakarthik70@gmail.com], and phone number [+1 (917) 914-0591], and successfully registering the account, I logged out to create a new account with the username [Karthik2], and the same email and phone number as above, and I was able to successfully register again

PS: However, Reset Password flow works well in this case, because it asks for both username and email, and the reset link only changes the password for the right accounts

**Comment by aryanprasad7** [comment]
Though ur concern is valid, we would like to bring this question to the professor in our presentation on Monday, after his input on our perspective, we will think if we need to update the case.

**Comment by ShambhaviSeth** [comment]
This is working as expected because we want to provide the option for the provider to be able to register as a user too.
Closing this issue hence.
