### ISSUE TITLE
Providers Favorites/Unfavorites Alerts after Logging out

### ISSUE THREAD

**Issue by KarthikVV24-11-1999** [gcivil-nyu-org/fall24-monday-team5#86]
Account used: test2_user
Bug: Getting Alerts after Logging out
Steps Followed: 
```
1. Login into the account
2. Go to Browse Providers
3. Select a Provider (Test 2 Provider)
4. Favorite/Unfavorite the Provider (as many times as you like)
5. Logout
```
Expected Results: Should not have any Alerts after logging out

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVhhQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3512e4ae541372204d0a06f61d5862a14305aa87/Screen%20Recording%202024-11-21%20at%201.44.46%E2%80%AFPM.mov)

**Comment by aryanprasad7** [comment]
Thanks for pointing this out Karthik, we were aware of this issue, but weren't able to update the document for this on time. 
The fix was supposed to be done in the next sprint.
